library(lubridate)
library(dplyr)

file_url<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(file_url, "electric.zip")
unzip("electric.zip")
estimate_size<-2075259*9*8/(1024*1024)
hpc<-read.table("household_power_consumption.txt", sep=";", header = TRUE)
hpc$Date<-dmy(hpc$Date)
hpc$Time<-hms(hpc$Time)
date_select<-interval(ymd("2007-02-01"),ymd("2007-02-02"))
hpc3<-subset(hpc,Date %within% date_select)
hpc4<-mutate(hpc3, NewTime=Date+Time)
png(file="plot4.png")
par(mfrow=c(2,2))
plot(hpc4$NewTime,as.numeric(hpc4$Global_active_power), type="l", xlab="", ylab="Global Active Power")
plot(hpc4$NewTime,as.numeric(hpc4$Voltage), type="l", xlab="datetime", ylab="Voltage")
plot(hpc4$NewTime,as.numeric(hpc4$Sub_metering_1), type="n", xlab="", ylab="Energy sub metering")
points(hpc4$NewTime, hpc4$Sub_metering_1,type="l", col="black")
points(hpc4$NewTime, hpc4$Sub_metering_2,type="l", col="red")
points(hpc4$NewTime, hpc4$Sub_metering_3,type="l", col="blue")
legend("topright", lwd=1, col=c("black", "red", "blue"),
       legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex=0.9,bty="n")
plot(hpc4$NewTime,as.numeric(hpc4$Global_reactive_power), type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()